# Generated by Django 5.1.1 on 2024-10-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
