# Generated by Django 5.1.1 on 2024-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='page_link_location',
            field=models.CharField(choices=[('navbar', 'Navbar'), ('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('unsorted', 'Unsorted')], default='unsorted', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='page_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_link_location',
            field=models.CharField(choices=[('navbar', 'Navbar'), ('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('unsorted', 'Unsorted')], default='unsorted', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=10),
        ),
    ]
