# Generated by Django 5.1.1 on 2024-10-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0002_alter_link_page_link_location_alter_link_page_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='page_link_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='page_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='link',
            name='show_in_position',
        ),
        migrations.AlterField(
            model_name='link',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='cms_content.page'),
        ),
    ]
