# Generated by Django 5.1.1 on 2024-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
