# Generated by Django 5.1.1 on 2024-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0007_post_author_post_excerpt_post_status_post_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=10),
        ),
    ]
