# Generated by Django 5.1.1 on 2024-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0008_remove_page_order_remove_page_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
